.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EMAD 1 "July 26, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
emad \- He is trapped!  Get him out!
.SH SYNOPSIS
.B emad
.\" .RI [ -hny ] 
.SH DESCRIPTION
Miss Cleo has put Emad in a mindjail, which is a prison for your
mind.  It is your job to get him out!

Use the arrow keys on your keyboard, or the standard nethack or
vi movement keys to maneuver Emad.  The \fBc\fP key transforms
Emad into his cybernetic alter-ego, and subsequently fires his
arm-mounted laser cannon. A series of non-emad figures may be
cycled through with the \fBs\fP command. The \fBe\fP key returns
him to his normal emadic state.  

Regrettably, neither \fBq\fP nor \fB^C\fP quit.  It is up to
\fIyou\fP to determine how to escape the mindjail.

.SH SEE ALSO
.BR mindjail (1).
.SH AUTHOR
This manual page was written by Nick Moffitt <nick@zork.net>.
