name: ci
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependency packages
      run: |
        sudo apt-get -y install build-essential gnulib pkg-config
        sudo apt-get -y install libncursesw5-dev || true
        sudo apt-get -y install libncurses-dev || true
    - name: autoreconf
      run: autoreconf -ifv
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Upload dist     
      uses: actions/upload-artifact@v2
      with:
        name: emad-dist-${{ github.job }}-${{ github.run_id }}.${{ github.run_number }}
        path: emad-*.tar.gz
