# SPDX-PackageName: emad
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/emad
# SPDX-FileComment: GitHub Actions ci workflow
# SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: GPL-2.0-or-later
---
name: "ci"
"on": ["push", "pull_request"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Dependency packages"
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential gnulib pkg-config
          sudo apt-get -y install libncursesw5-dev || true
          sudo apt-get -y install libncurses-dev || true
      - name: "Build"
        run: |
          autoreconf -ifv
          ./configure
          make
      - name: "Test"
        run: |
          make check
          make distcheck
      - name: "Upload dist"
        uses: "actions/upload-artifact@v7"
        with:
          name: "emad-dist-${{ github.job }}-${{ github.run_id }}.${{ github.run_number }}"
          path: "emad-*.tar.gz"
